/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

import DAO.FornecedorDAO;
import Modelo.Fornecedor;
import ModeloTabela.TabelaFornecedor;
import java.sql.SQLException;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.text.DefaultFormatterFactory;
import javax.swing.text.MaskFormatter;

/**
 *
 * @author DarthVader
 */
public class FornecedorInter extends javax.swing.JFrame {

    /**
     * Creates new form FornecedorInter
     */
    FornecedorDAO dao = new FornecedorDAO();
    Fornecedor fornecedor = new Fornecedor();
    TabelaFornecedor tabela = new TabelaFornecedor();

    public FornecedorInter() {
        initComponents();
        jTableFornc.setModel(tabela);
        Tabela();
        try {
            MaskFormatter cnpj = new MaskFormatter("##.###.###/####-##");
            jTextFieldCNPJ.setFormatterFactory(new DefaultFormatterFactory(cnpj));
            MaskFormatter tel = new MaskFormatter("(##) #####-####");
            jTextFieldTelefone.setFormatterFactory(new DefaultFormatterFactory(tel));

        } catch (ParseException ex) {
            Logger.getLogger(FornecedorInter.class.getName()).log(Level.SEVERE, null, ex);
        }

        jButtonAlterar.setEnabled(false);
    }

    public void Tabela() {
        try {
            for (Fornecedor fornecedor : dao.ListaForn()) {
                tabela.addRow(fornecedor);
            }

            jTableFornc.getColumnModel().getColumn(0).setPreferredWidth(80);
            jTableFornc.getColumnModel().getColumn(0).setResizable(false);
            jTableFornc.getColumnModel().getColumn(1).setPreferredWidth(450);
            jTableFornc.getColumnModel().getColumn(1).setResizable(false);
            jTableFornc.getColumnModel().getColumn(2).setPreferredWidth(160);
            jTableFornc.getColumnModel().getColumn(2).setResizable(false);
            jTableFornc.getColumnModel().getColumn(3).setPreferredWidth(165);
            jTableFornc.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
            jTableFornc.setRowHeight(22);
            jTableFornc.setAutoResizeMode(jTableFornc.AUTO_RESIZE_OFF);

        } catch (SQLException ex) {
            Logger.getLogger(FornecedorInter.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public void Tabela2(String nome) {
        try {
            for (Fornecedor fornecedor : dao.ListaForn2(nome)) {
                tabela.addRow(fornecedor);

            }
            jTableFornc.getColumnModel().getColumn(0).setPreferredWidth(80);
            jTableFornc.getColumnModel().getColumn(0).setResizable(false);
            jTableFornc.getColumnModel().getColumn(1).setPreferredWidth(450);
            jTableFornc.getColumnModel().getColumn(1).setResizable(false);
            jTableFornc.getColumnModel().getColumn(2).setPreferredWidth(160);
            jTableFornc.getColumnModel().getColumn(2).setResizable(false);
            jTableFornc.getColumnModel().getColumn(3).setPreferredWidth(165);
            jTableFornc.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
            jTableFornc.setRowHeight(22);
            jTableFornc.setAutoResizeMode(jTableFornc.AUTO_RESIZE_OFF);
        } catch (SQLException ex) {
            Logger.getLogger(FornecedorInter.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTextFieldCodigo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldNome_Fanstasia = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldCNPJ = new javax.swing.JFormattedTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldEmail = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextFieldSite = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextFieldTempo_Entrega = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jTextFieldTelefone = new javax.swing.JFormattedTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldEndereco = new javax.swing.JTextField();
        jButtonPesquisar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableFornc = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jButtonGravar = new javax.swing.JButton();
        jButtonAlterar = new javax.swing.JButton();
        jButtonLimpar = new javax.swing.JButton();
        jButtonVoltar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Tela de cadastro de fornecedores");
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setPreferredSize(new java.awt.Dimension(710, 94));

        jTextFieldCodigo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextFieldCodigo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldCodigo.setEnabled(false);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel3.setText("Nome fantasia:");

        jTextFieldNome_Fanstasia.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextFieldNome_Fanstasia.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        jLabel1.setText("Cadastro de fornecedores");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel2.setText("Código:");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel4.setText("CNPJ:");

        jTextFieldCNPJ.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldCNPJ.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel6.setText("E-mail:");

        jTextFieldEmail.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextFieldEmail.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel7.setText("Site:");

        jTextFieldSite.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextFieldSite.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel8.setText("Tempo de entrega:");

        jTextFieldTempo_Entrega.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextFieldTempo_Entrega.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldTempo_Entrega.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldTempo_EntregaActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel9.setText("Dias úteis");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel10.setText("Telefone:");

        jTextFieldTelefone.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldTelefone.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel5.setText("Endereço:");

        jTextFieldEndereco.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextFieldEndereco.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jButtonPesquisar.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jButtonPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/Report-Magnify-32.png"))); // NOI18N
        jButtonPesquisar.setText("Pesquisar");
        jButtonPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPesquisarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldTempo_Entrega, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel9)
                        .addGap(105, 105, 105)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(121, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldEndereco))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldCNPJ, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldSite))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldNome_Fanstasia, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButtonPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(21, 21, 21))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(222, 222, 222))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jTextFieldNome_Fanstasia, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextFieldCNPJ, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jTextFieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(jTextFieldSite, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jTextFieldTempo_Entrega, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(jTextFieldTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextFieldEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED), "Fornecedores cadastrados", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 16))); // NOI18N

        jTableFornc.setAutoCreateRowSorter(true);
        jTableFornc.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jTableFornc.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTableFornc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableForncMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableFornc);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 194, Short.MAX_VALUE)
        );

        jPanel3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jButtonGravar.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jButtonGravar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/Report-Disk-32.png"))); // NOI18N
        jButtonGravar.setText("Gravar");
        jButtonGravar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonGravar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGravarActionPerformed(evt);
            }
        });

        jButtonAlterar.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jButtonAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/Report-Edit-32.png"))); // NOI18N
        jButtonAlterar.setText("Alterar");
        jButtonAlterar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAlterarActionPerformed(evt);
            }
        });

        jButtonLimpar.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jButtonLimpar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/Report-32.png"))); // NOI18N
        jButtonLimpar.setText("Limpar");
        jButtonLimpar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLimparActionPerformed(evt);
            }
        });

        jButtonVoltar.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jButtonVoltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/download.png"))); // NOI18N
        jButtonVoltar.setText("Voltar");
        jButtonVoltar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVoltarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonGravar, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonGravar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 244, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49))
        );

        setSize(new java.awt.Dimension(903, 539));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldTempo_EntregaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldTempo_EntregaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldTempo_EntregaActionPerformed

    private void jButtonGravarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGravarActionPerformed
        // TODO add your handling code here:
        // validação de campos, verificar se não estão vazios.
        if ((jTextFieldNome_Fanstasia.getText().isEmpty()) || (jTextFieldCNPJ.getText().isEmpty()) || (jTextFieldTelefone.getText().isEmpty())
                || (jTextFieldEndereco.getText().isEmpty()) || (jTextFieldSite.getText().isEmpty()) || (jTextFieldEmail.getText().isEmpty())
                || (jTextFieldTempo_Entrega.getText().isEmpty())) {
            JOptionPane.showMessageDialog(null, "Os campos não podem estar em branco!");
        } else {
            // Instancia um objeto da classe funcionario e insere valores nas variaveis.

            long tempo = Long.parseLong(jTextFieldTempo_Entrega.getText());

            fornecedor.setCNPJ(jTextFieldCNPJ.getText());
            fornecedor.setNome_fantasia(jTextFieldNome_Fanstasia.getText());
            fornecedor.setEndereco(jTextFieldEndereco.getText());
            fornecedor.setEmail(jTextFieldEmail.getText());
            fornecedor.setTelefone(jTextFieldTelefone.getText());
            fornecedor.setTempo_entrega(tempo);
            fornecedor.setSite(jTextFieldSite.getText());

            /**
             * instanciar a classe FuncionarioCRUD do pacote CRUD e cria seu
             * objeto, para fazer a inserção das informações no banco de dados
             */
            FornecedorDAO dao = new FornecedorDAO();

            dao.adicionaFornecedor(fornecedor);
            JOptionPane.showMessageDialog(null, "Fornecedor " + jTextFieldNome_Fanstasia.getText() + " inserido com sucesso! ");
        }

        // Realiza a limpeza dos campos após a inserção.    
        jTextFieldNome_Fanstasia.setText("");
        jTextFieldCNPJ.setText("");
        jTextFieldEndereco.setText("");
        jTextFieldEmail.setText("");
        jTextFieldTempo_Entrega.setText("");
        jTextFieldTelefone.setText("");
        jTextFieldSite.setText("");

    }//GEN-LAST:event_jButtonGravarActionPerformed

    private void jButtonVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVoltarActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButtonVoltarActionPerformed

    private void jButtonAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAlterarActionPerformed
        // TODO add your handling code here:
        if ((jTextFieldNome_Fanstasia.getText().isEmpty()) || (jTextFieldCNPJ.getText().isEmpty()) || (jTextFieldTelefone.getText().isEmpty())
                || (jTextFieldEndereco.getText().isEmpty()) || (jTextFieldSite.getText().isEmpty()) || (jTextFieldEmail.getText().isEmpty())
                || (jTextFieldTempo_Entrega.getText().isEmpty())) {

            JOptionPane.showMessageDialog(null, "Os campos não podem estar em branco!");

        } else {

            long cod = Long.parseLong(jTextFieldCodigo.getText());
            long dia = Long.parseLong(jTextFieldTempo_Entrega.getText());

            fornecedor.setCNPJ(jTextFieldCNPJ.getText());
            fornecedor.setNome_fantasia(jTextFieldNome_Fanstasia.getText());
            fornecedor.setEndereco(jTextFieldEndereco.getText());
            fornecedor.setEmail(jTextFieldEmail.getText());
            fornecedor.setTelefone(jTextFieldTelefone.getText());
            fornecedor.setTempo_entrega(dia);
            fornecedor.setSite(jTextFieldSite.getText());

            dao.AlteraFornc(fornecedor, cod);

            JOptionPane.showMessageDialog(null, "Cadastro alterado com sucesso!");

            jButtonAlterar.setEnabled(false);
            jButtonGravar.setEnabled(true);

            jTextFieldNome_Fanstasia.setText("");
            jTextFieldCNPJ.setText("");
            jTextFieldEndereco.setText("");
            jTextFieldEmail.setText("");
            jTextFieldTempo_Entrega.setText("");
            jTextFieldTelefone.setText("");
            jTextFieldSite.setText("");

        }
    }//GEN-LAST:event_jButtonAlterarActionPerformed

    private void jButtonPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPesquisarActionPerformed
        // TODO add your handling code here:

        if (jTextFieldNome_Fanstasia.getText().isEmpty() && jTextFieldCNPJ.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Para realizar uma busca digite o CNPJ ou o nome do fornecedor");
            jTextFieldCNPJ.grabFocus();
        } else if (!jTextFieldCNPJ.getText().isEmpty()) {
            dao.buscaFornecedor(fornecedor, jTextFieldCNPJ.getText());

            JOptionPane.showMessageDialog(null, "Busca realizada com sucesso!");

            String cod = String.valueOf(fornecedor.getCod_Fornc());
            String dia = String.valueOf(fornecedor.getTempo_entrega());

            jTextFieldCodigo.setText(cod);
            jTextFieldEmail.setText(fornecedor.getEmail());
            jTextFieldEndereco.setText(fornecedor.getEndereco());
            jTextFieldNome_Fanstasia.setText(fornecedor.getNome_fantasia());
            jTextFieldSite.setText(fornecedor.getSite());
            jTextFieldTelefone.setText(fornecedor.getTelefone());
            jTextFieldTempo_Entrega.setText(dia);

            jButtonAlterar.setEnabled(true);
            jButtonGravar.setEnabled(false);
            
        } else if (!jTextFieldNome_Fanstasia.getText().isEmpty()) {
            tabela.atualiza();
            jTableFornc.setModel(tabela);
            Tabela2(jTextFieldNome_Fanstasia.getText());
        }
    }//GEN-LAST:event_jButtonPesquisarActionPerformed

    private void jTableForncMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableForncMouseClicked
        // TODO add your handling code here:
        if (jTableFornc.getSelectedRow() != -1) {

            jTextFieldNome_Fanstasia.setText("");
            jTextFieldCNPJ.setText("");
            jTextFieldEndereco.setText("");
            jTextFieldEmail.setText("");
            jTextFieldTempo_Entrega.setText("");
            jTextFieldTelefone.setText("");
            jTextFieldSite.setText("");
            jTextFieldCodigo.setText("");

            jButtonAlterar.setEnabled(true);
            jButtonGravar.setEnabled(false);

            dao.buscaFornecedor(fornecedor, jTableFornc.getValueAt(jTableFornc.getSelectedRow(), 2).toString());

            String cod = String.valueOf(fornecedor.getCod_Fornc());
            String dia = String.valueOf(fornecedor.getTempo_entrega());

            jTextFieldCNPJ.setText(jTableFornc.getValueAt(jTableFornc.getSelectedRow(), 2).toString());
            jTextFieldCodigo.setText(cod);
            jTextFieldEmail.setText(fornecedor.getEmail());
            jTextFieldEndereco.setText(fornecedor.getEndereco());
            jTextFieldNome_Fanstasia.setText(fornecedor.getNome_fantasia());
            jTextFieldSite.setText(fornecedor.getSite());
            jTextFieldTelefone.setText(fornecedor.getTelefone());
            jTextFieldTempo_Entrega.setText(dia);

        }
    }//GEN-LAST:event_jTableForncMouseClicked

    private void jButtonLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLimparActionPerformed
        // TODO add your handling code here:
        jTextFieldNome_Fanstasia.setText("");
        jTextFieldCNPJ.setText("");
        jTextFieldEndereco.setText("");
        jTextFieldEmail.setText("");
        jTextFieldTempo_Entrega.setText("");
        jTextFieldTelefone.setText("");
        jTextFieldSite.setText("");
        jTextFieldCodigo.setText("");

        jButtonAlterar.setEnabled(!true);
        jButtonGravar.setEnabled(!false);
    }//GEN-LAST:event_jButtonLimparActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FornecedorInter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FornecedorInter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FornecedorInter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FornecedorInter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FornecedorInter().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAlterar;
    private javax.swing.JButton jButtonGravar;
    private javax.swing.JButton jButtonLimpar;
    private javax.swing.JButton jButtonPesquisar;
    private javax.swing.JButton jButtonVoltar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableFornc;
    private javax.swing.JFormattedTextField jTextFieldCNPJ;
    private javax.swing.JTextField jTextFieldCodigo;
    private javax.swing.JTextField jTextFieldEmail;
    private javax.swing.JTextField jTextFieldEndereco;
    private javax.swing.JTextField jTextFieldNome_Fanstasia;
    private javax.swing.JTextField jTextFieldSite;
    private javax.swing.JFormattedTextField jTextFieldTelefone;
    private javax.swing.JTextField jTextFieldTempo_Entrega;
    // End of variables declaration//GEN-END:variables
}
